# Generated by Django 6.0.6 on 2026-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
    ]
